apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: feelz
  namespace: argocd
spec:
  destinations:
  - namespace: feelz
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/unifist/platform
