apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ledger
  namespace: argocd
spec:
  destinations:
  - namespace: ledger
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/unifist/platform
